# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 03:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('memo_notes', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
                ('employee_name', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=35)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Menu_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('is_cashed', models.BooleanField(default=False)),
                ('table_number', models.IntegerField()),
                ('is_server', models.CharField(max_length=30)),
                ('is_completed', models.BooleanField(default=False)),
                ('memo_notes', models.CharField(blank=True, max_length=30, null=True)),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('total_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Menu')),
            ],
            options={
                'ordering': ('table_number',),
            },
        ),
        migrations.AddField(
            model_name='check',
            name='check_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order'),
        ),
        migrations.AddField(
            model_name='check',
            name='price',
            field=models.ManyToManyField(to='app.Menu'),
        ),
        migrations.AddField(
            model_name='check',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
