# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_drinkoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='openticket',
            name='guest_drink',
            field=models.ManyToManyField(to='app.DrinkOptions'),
        ),
    ]
