# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_openticket_guest_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkoptions',
            name='cost',
            field=models.FloatField(),
        ),
    ]
